# Numpy Basics


### How to create an array using numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print(a[2])
a[2] = 10
print(a)

[1 2 3 4 5]
3
[ 1  2 10  4  5]


### The dimensional values


In [41]:
a_mul = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a_mul[0][1])
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

2
(3, 3)
2
9
int64


### accessing the data type of each element

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], ["7", 8, 9]], dtype=np.float64)

print(a.dtype)
print(a[1][0].dtype)
print(a[2][0])

float64
float64
7.0


### options like creating an array with single values

In [ ]:
a = np.full((2, 3), 1)
print(a)

print("\n")

b = np.ones((1, 5))
print(b)

print("\n")

c = np.empty((3, 2))
print(c)

[[1 1 1]
 [1 1 1]]


[[1. 1. 1. 1. 1.]]


[[5.e-324 5.e-324]
 [5.e-324 5.e-324]
 [5.e-324 5.e-324]]


### Creating random datas from a given range with intervals

In [ ]:
x_val = np.arange(0, 1000, 15)
print(x_val)

print("\n")

y_val = np.linspace(0, 2, 100)
print(y_val)

[  0  15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255
 270 285 300 315 330 345 360 375 390 405 420 435 450 465 480 495 510 525
 540 555 570 585 600 615 630 645 660 675 690 705 720 735 750 765 780 795
 810 825 840 855 870 885 900 915 930 945 960 975 990]


[0.         0.02020202 0.04040404 0.06060606 0.08080808 0.1010101
 0.12121212 0.14141414 0.16161616 0.18181818 0.2020202  0.22222222
 0.24242424 0.26262626 0.28282828 0.3030303  0.32323232 0.34343434
 0.36363636 0.38383838 0.4040404  0.42424242 0.44444444 0.46464646
 0.48484848 0.50505051 0.52525253 0.54545455 0.56565657 0.58585859
 0.60606061 0.62626263 0.64646465 0.66666667 0.68686869 0.70707071
 0.72727273 0.74747475 0.76767677 0.78787879 0.80808081 0.82828283
 0.84848485 0.86868687 0.88888889 0.90909091 0.92929293 0.94949495
 0.96969697 0.98989899 1.01010101 1.03030303 1.05050505 1.07070707
 1.09090909 1.11111111 1.13131313 1.15151515 1.17171717 1.19191919
 1.21212121 1.23232323 1.25252525 1.27272727 1.29292929 

### Learning about Null and Infinite values

In [ ]:
print(np.nan)
print(np.inf)

print(np.isnan(np.nan))
print(np.isinf(np.nan))

nan
inf
True
False


### Operations that can be done in numpy which cannot be done in list concept



In [ ]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 2)
print(a1 * 2)

print(a1 + 5)
print(a1 - 5)
print(a1 * a2)
print(a1 / a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 6 14 24 36  0]
[0.16666667 0.28571429 0.375      0.44444444        inf]


C:\Users\nikil\AppData\Local\Temp\ipykernel_18368\2183510233.py:13: RuntimeWarning: divide by zero encountered in divide
  print(a1/a2)


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1], [2]])

print(a1 + a2)

[[2 3 4]
 [3 4 5]]


### Mathematical functions in numpy

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.exp(a))
print(np.log10(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


### data accessing functions 

In [ ]:
a = np.array([1, 2, 3])
a = np.append(a, [7, 8, 9])
print(a)

a = np.insert(a, 3, [4, 5, 6])
print(a)

print(np.delete(a, 1))

a = np.array([[1, 2, 3], [4, 5, 6]])

print(np.delete(a, 2, 1))

[1 2 3 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 4 5 6 7 8 9]
[[1 2]
 [4 5]]


### reshaping of array


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print("\n")
print(a.reshape(3, 2))
a.resize(3, 2)
print(a)


print(a.flatten())
print(a.ravel())

(2, 3)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
a = np.array(
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
)
print(a)
print("\n")

print(a.transpose())
print("\n")
print(a.T)
print("\n")
print(a.swapaxes(0, 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


### concatinating and stacking 

In [ ]:
a1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a2 = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
a = np.concatenate((a1, a2), axis=1)
print(a)


b = np.stack((a1, a2))
print(b)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


### Spilliting of array

In [203]:
a = np.array(
    [
        [1, 2, 3, 4, 5, 50],
        [6, 7, 8, 9, 10, 100],
        [11, 12, 13, 14, 15, 150],
        [16, 17, 18, 19, 20, 200],
    ]
)


print(np.split(a, 2, axis=1))

[array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]]), array([[  4,   5,  50],
       [  9,  10, 100],
       [ 14,  15, 150],
       [ 19,  20, 200]])]


### arithmetic functions

In [218]:
a = np.array(
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
)


print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())

1
20
10.5
5.766281297335398
210


### random number generating in array


In [ ]:
num = np.random.randint(100, 200, size=(2, 4))
print(num)

n = np.random.choice([10, 20, 30, 40, 50])
print(n)

[[123 124 172 176]
 [131 155 154 110]]
40
