# Mathematical Analysis of a matrix


### Importing modules

In [34]:
import numpy as np

### Coding the function

In [ ]:
def array_init(m, n):
    arr = np.random.randint(1, 500, size=(m, n))
    return arr

if __name__ == "__main__":
    m = int(input("Enter size m of mxn matrix: "))
    n = int(input("Enter size n of mxn matrix: "))
    data = array_init(m, n)
    print(data)
    print("\n")
    print(f"Mean: {np.mean(data):.2f}")
    print(f"Medain: {np.median(data)}")
    print(f"Standard Deviation: {np.std(data):.2f}")
    print(f"Variance: {np.var(data):.2f}")
    print(f"Maximum value: {np.max(data)}")
    print(f"Minimum value: {np.min(data)}")
    print(f"Transponse of matrix: \n{ data.T}")
    print(f"Coefficient Correlation of matrix: \n{np.corrcoef(data.T)}")



[[338 481 153]
 [102 395 265]
 [264  12 169]]


Mean: 242.11
Medain: 264.0
Standard Deviation: 140.04
Variance: 19612.10
Maximum value: 481
Minimum value: 12
Transponse of matrix: 
[[338 102 264]
 [481 395  12]
 [153 265 169]]
Coefficient Correlation of matrix: 
[[ 1.         -0.03895484 -0.98400489]
 [-0.03895484  1.          0.21633801]
 [-0.98400489  0.21633801  1.        ]]
